import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {TRAFFIC_ROUTES,routePoint,createTraffic,updateTraffic,resolveTraffic,trafficOnBridge,trafficStop,assistTraffic,contact} from '../public/games/sunset/traffic.js';
import {createCar,updateCar,carBlocked} from '../public/games/sunset/vehicle.js';import {createWaterfront,updateWaterfront,bridgeBoxes} from '../public/games/sunset/waterfront.js';import {createHarborTour,harborInput} from '../public/games/sunset/harbor-tour.js';
const layout=()=>JSON.parse(fs.readFileSync(new URL('../public/games/sunset/world-layout.json',import.meta.url)));
test('four traffic lane loops have full body clearance at every meter',()=>{const l=layout();for(const [i,r]of TRAFFIC_ROUTES.entries())for(let s=0;s<r.length;s++)assert.equal(carBlocked(routePoint(r,s),l),false,JSON.stringify({i,s}));});
test('red light, pedestrian, queue and bridge each request a traffic stop',()=>{const t=createTraffic(),w=createWaterfront();t.cars=[];t.time=18;const c={x:2.55,z:-20,angle:Math.PI};assert.equal(trafficStop(c,t,null,null,w).reason,'signal');t.time=0;assert.equal(trafficStop(c,t,null,{x:2.55,z:-26},w).reason,'pedestrian');t.cars=[{x:2.55,z:-28,angle:Math.PI}];assert.equal(trafficStop(c,t,null,null,w).reason,'vehicle');t.cars=[];w.phase='warning';assert.equal(trafficStop({...c,z:-252},t,null,null,w).reason,'bridge');});
test('ten traffic vehicles and full harbor tour finish without a collision at 30 and 60Hz',()=>{for(const hz of [30,60]){const l=layout(),t=createTraffic(),c={...createCar(),occupied:true,obeyTraffic:true},w=createWaterfront(),tour=createHarborTour();l.waterfront=()=>w;l.obstacles=()=>bridgeBoxes(w);let stopped=false;for(let i=0;i<420*hz;i++){updateWaterfront(w,1/hz,c,null,false,trafficOnBridge(t));updateTraffic(t,1/hz,c,null,w,l);updateCar(c,assistTraffic(harborInput(tour,c,w,1/hz),c,t,w),1/hz,l);resolveTraffic(t,c,l);stopped||=t.cars.some(c=>c.stoppedFor==='bridge');if(tour.finished)break;}assert.ok(tour.finished,JSON.stringify({hz,tour,c}));assert.equal(t.impacts,0);assert.ok(stopped);assert.ok(w.cycles>=2);assert.ok(t.cars.every(c=>c.mode==='lane'&&!carBlocked(c,l)));}});
test('head-on impact transfers momentum and cosmetic damage, recovery rejoins the lane without teleporting',()=>{for(const hz of [30,60,120]){const l=layout(),t=createTraffic(),w=createWaterfront();t.cars=[t.cars[0]];const c={...createCar(),x:-2.55,z:-124,angle:Math.PI,speed:13,occupied:true},npc=t.cars[0];npc.s=TRAFFIC_ROUTES[0].segments.find(p=>p.z>-146&&p.z<-145&&p.x>-3).start;Object.assign(npc,routePoint(TRAFFIC_ROUTES[0],npc.s));let impacted=false,maxStep=0;for(let i=0;i<40*hz;i++){const before={x:npc.x,z:npc.z};updateTraffic(t,1/hz,c,null,w,l);updateCar(c,{throttle:impacted?-1:1,steer:0,brake:impacted&&c.z>-117},1/hz,l);resolveTraffic(t,c,l);impacted||=t.impacts>0;maxStep=Math.max(maxStep,Math.hypot(npc.x-before.x,npc.z-before.z));}assert.ok(impacted);assert.ok(c.damage>0&&npc.damage>0);assert.ok(maxStep<.8,`${hz}: ${maxStep}`);assert.ok(!carBlocked(c,l)&&!carBlocked(npc,l));assert.equal(npc.mode,'lane');}});
test('side impact rotates a traffic vehicle, repeated overlap does not repeatedly award damage, pause is exact',()=>{const t=createTraffic(),l=layout();t.cars=[{...t.cars[0],x:0,z:-125,angle:0,speed:0}];const c={...createCar(),x:-3,z:-125,angle:Math.PI/2,speed:10,occupied:true};assert.ok(contact(c,t.cars[0]));resolveTraffic(t,c,l);assert.ok(Math.abs(t.cars[0].spin)>.1);const impacts=t.impacts;resolveTraffic(t,c,l);assert.equal(t.impacts,impacts);const snap=structuredClone(t);updateTraffic(t,10,c,null,createWaterfront(),l,true);assert.deepEqual(t,snap);});
